var city_codes = {
"frxab" : "Abbeville",
"frmlw" : "Aéroport CDG 2 TGV",
"frxag" : "Agde",
"fragf" : "Agen",
"frais" : "Ailly Sur Somme",
"frqai" : "Aime la Plagne",
"frqxb" : "Aix en Provence",
"fraie" : "Aix en Provence TGV",
"frxai" : "Aix les Bains le Revard",
"frale" : "Albens",
"frxav" : "Albertville",
"frafj" : "Albi ville",
"frxan" : "Alençon",
"fralc" : "Allassac",
"framb" : "Ambérieu",
"frqam" : "Amiens",
"frefn" : "Ancenis",
"fracl" : "Angers St Laud",
"frang" : "Angoulême",
"frncy" : "Annecy",
"frqnj" : "Annemasse",
"frxat" : "Antibes",
"frxac" : "Arcachon",
"frart" : "Argentan",
"frhza" : "Arles",
"frqrv" : "Arras",
"frauh" : "Auch",
"frxoy" : "Aulnoye Aymeries",
"frxuy" : "Auray",
"frhiq" : "Aurec",
"fraur" : "Aurillac",
"frasg" : "Auxerre Saint Gervais",
"fraes" : "Avignon Centre",
"frihw" : "Avignon Sud",
"fravg" : "Avignon TGV",
"frxbd" : "Bar le Duc",
"frhit" : "Bas-Monistrol",
"frxby" : "Bayonne",
"frxbv" : "Beaune",
"frbor" : "Belfort",
"frtja" : "Belfort Montbéliard TGV",
"frxbf" : "Bellegarde",
"fregc" : "Bergerac",
"frtjb" : "Besançon Franche-Comté TGV",
"frabg" : "Besançon Viotte",
"frxbh" : "Béthune",
"frbzr" : "Béziers",
"frbiq" : "Biarritz",
"frfac" : "Biganos - Facture",
"frxbq" : "Blois",
"frhtv" : "Bonneville",
"frhsl" : "Bons en Chablais",
"frboj" : "Bordeaux St-Jean",
"fraeb" : "Boulogne Ville",
"frxbk" : "Bourg en Bresse",
"frbou" : "Bourges",
"frqbm" : "Bourg St Maurice",
"frbss" : "Boussens",
"frbes" : "Brest",
"frxbc" : "Briançon",
"frhvv" : "Brignoud",
"frbve" : "Brive La Gaillarde",
"frcfr" : "Caen",
"frzao" : "Cahors",
"frsth" : "Calais Frethun",
"fraea" : "Calais Ville",
"frafx" : "Cambrai",
"frjca" : "Cannes",
"frccf" : "Carcassonne",
"frcty" : "Castelnaudary",
"frhvj" : "Châbons",
"frcgy" : "Chagny",
"frxcr" : "Chalons en Champagne",
"frxcd" : "Chalon sur Saône",
"frcmf" : "Chambéry - Challes Les Eaux",
"freah" : "Champagne Ardenne TGV",
"frxcz" : "Charleville Mézières",
"frqtj" : "Chartres",
"frchr" : "Châteauroux",
"frxcy" : "Château Thierry",
"frxcx" : "Châtellerault",
"frxcw" : "Chaumont",
"frack" : "Cherbourg",
"frcfe" : "Clermont Ferrand",
"frhcl" : "Clermont-La Rotonde",
"frcli" : "Clisson",
"frhtz" : "Cluses",
"fraej" : "Colmar",
"frgag" : "Commentry",
"frxcp" : "Compiègne",
"frgsh" : "Cosne sur Loire",
"frcsf" : "Creil",
"frckh" : "Croix - Wasquehal",
"frccy" : "Culmont - Chalindrey",
"frcuz" : "Culoz",
"fracg" : "Dax",
"frgth" : "Decize",
"frafd" : "Dieppe",
"fraba" : "Dijon Ville",
"frdol" : "Dol",
"frace" : "Dole Ville",
"frdon" : "Don Sainghin",
"frxdn" : "Douai",
"frxdr" : "Dreux",
"fradi" : "Dunkerque",
"frece" : "Echirolles",
"frxep" : "Epernay",
"frepl" : "Epinal",
"freta" : "Etaples-le Touquet",
"frxeb" : "Evian les Bains",
"frevx" : "Evreux Normandie",
"frbqt" : "Forbach",
"frfra" : "Frasne",
"frfro" : "Frouard",
"frtgo" : "Futuroscope",
"frgan" : "Gannat",
"frgat" : "Gap",
"frhvx" : "Goncelin",
"frfsi" : "Gourdon",
"frgfr" : "Granville",
"frgnb" : "Grenoble",
"frhvs" : "Grenoble Universités Gières",
"frhtb" : "Grésy sur Aix",
"frhto" : "Groisy-Thorens-la-Caille",
"frxgt" : "Guéret",
"frggp" : "Guingamp",
"frhzk" : "Hazebrouck",
"fraef" : "Hendaye",
"frxhe" : "Hyères",
"frgmu" : "Joigny",
"frjsy" : "Juvisy TGV",
"frjee" : "La Baule Escoublac",
"frgsl" : "La Charité",
"frefz" : "La Haie Fouassière",
"frlam" : "Lamballe",
"frley" : "Lancey",
"frxld" : "Landerneau",
"frhpg" : "Landry",
"frlag" : "Langres",
"frlnz" : "Lannemezan",
"frlai" : "Lannion",
"frlrh" : "La Rochelle Ville",
"frisi" : "Laroche Migennes",
"frlrf" : "La Roche sur Foron",
"frxro" : "La Roche sur Yon",
"frlst" : "La Souterraine",
"frfcj" : "La Teste",
"fracr" : "Laval",
"frxcc" : "Le Creusot TGV",
"fregu" : "Le Croisic",
"frhvk" : "Le Grand Lemps",
"fraez" : "Le Havre",
"fraet" : "Le Mans",
"frxle" : "Lens",
"frega" : "Le Pallet",
"fregs" : "Le Pouliguen",
"frlpy" : "Le Puy en Velay",
"frxrs" : "Les Arcs Draguignan",
"frlab" : "Les Aubrais Orléans",
"frlso" : "Les Sables d'Olonne",
"frhls" : "Lezoux",
"frxlr" : "Libourne",
"frlle" : "Lille Europe",
"fradj" : "Lille Flandres",
"fragq" : "Limoges Bénédictins",
"frxlx" : "Lisieux",
"frcql" : "Longueau",
"frlwy" : "Longwy",
"frxll" : "Lons le Saunier",
"frlrt" : "Lorient",
"fream" : "Lorraine TGV",
"frlde" : "Lourdes",
"frlne" : "Lunéville",
"frlur" : "Lure",
"frhtf" : "Lyon Jean Macé",
"frlpd" : "Lyon Part Dieu",
"frlpe" : "Lyon Perrache",
"frjdq" : "Lyon St Exupéry TGV",
"frhsk" : "Machilly",
"frmlt" : "Macon Loche TGV",
"frhgu" : "Macon Ville",
"frhub" : "Magland",
"frmte" : "Mantes la Jolie",
"frhtw" : "Marigniers",
"frxmr" : "Marmande",
"frmlv" : "Marne la Vallée Chessy",
"frmsc" : "Marseille St Charles",
"frfkp" : "Masseret",
"frdju" : "Massy TGV",
"frxme" : "Maubeuge",
"frxmt" : "Menton",
"frade" : "Metz Ville",
"freaj" : "Meuse TGV",
"frmaz" : "Miramas",
"fragr" : "Modane",
"frabz" : "Moirans",
"frxmm" : "Monaco Monte Carlo",
"frgnx" : "Montargis",
"frxmw" : "Montauban Ville Bourbon",
"frgwe" : "Montbard",
"frxmf" : "Montbéliard",
"frmch" : "Montchanin",
"frxmj" : "Mont de Marsan",
"frxmk" : "Montélimar",
"frmcu" : "Montluçon Ville",
"frmml" : "Montmélian",
"frmpl" : "Montpellier St Roch",
"frgzg" : "Morez",
"frmxn" : "Morlaix",
"frmcd" : "Mouchard",
"frxmu" : "Moulins Sur Allier",
"frqmu" : "Moutiers Salins Brides-les-Bains",
"fraek" : "Mulhouse Ville",
"frenc" : "Nancy Ville",
"frnte" : "Nantes",
"frxna" : "Narbonne",
"frnch" : "Neufchateau",
"frnvs" : "Nevers",
"frnic" : "Nice Ville",
"frfni" : "Nîmes",
"frnit" : "Niort",
"frgxc" : "Nuits Saint-Georges",
"frhqn" : "Nurieux",
"froil" : "Oissel",
"frxog" : "Orange",
"frafk" : "Orléans",
"frgfi" : "Orthez",
"froyo" : "Oyonnax",
"frpaz" : "Paris Austerlitz",
"frpbe" : "Paris Bercy",
"frpst" : "Paris Est",
"frply" : "Paris Gare de Lyon",
"frpmo" : "Paris Montparnasse",
"frpno" : "Paris Nord",
"frpsl" : "Paris St Lazare",
"fraee" : "Pau",
"frabf" : "Périgueux",
"frpgf" : "Perpignan",
"frhsn" : "Perrignier",
"frplt" : "Plouaret-Trégor",
"frpis" : "Poitiers",
"frifi" : "Poliénas",
"frptl" : "Pontarlier",
"frhvz" : "Pontcharra sur Bréda Allevard",
"frpdo" : "Pont de Dore le Chambon",
"fregr" : "Pornichet",
"frhtk" : "Pringy",
"fruip" : "Quimper",
"freco" : "Quimperlé",
"frcvu" : "Rang du Fliers - Verton - Berck",
"frhvn" : "Reaumont Saint-Cassien",
"frxrn" : "Redon",
"frhuf" : "Reignier",
"frrhe" : "Reims",
"frrnt" : "Remiremont",
"frrns" : "Rennes",
"frbdt" : "Rethel",
"frhms" : "Retournac",
"frrio" : "Riom-Châtel Guyon",
"frhvm" : "Rives",
"frrne" : "Roanne",
"frrco" : "Rochefort",
"frrdz" : "Rodez",
"frrsp" : "Rosporden",
"fradp" : "Roubaix",
"frurd" : "Rouen Rive Droite",
"frryn" : "Royan",
"frhko" : "Royat-Chamalières",
"frfds" : "Ruffec",
"frhte" : "Rumilly",
"frsab" : "Sablé",
"frsze" : "Saincaize",
"frsag" : "Saint-André le Gaz",
"frhoj" : "Saint-Avre la Chambre",
"frsbk" : "Saint-Brieuc",
"frhel" : "Saint-Clair les Roches",
"frxtd" : "Saint-Dié des Vosges",
"frhvr" : "Saint-Egrève-Saint-Robert",
"frxst" : "Saintes",
"frhhd" : "Saint-Etienne Châteaucreux",
"frsgf" : "Saint-Germain des Fossés",
"frxgf" : "Saint-Gervais les Bains Le Fayet",
"frity" : "Saint-Hilaire-Saint-Nazaire",
"frxjz" : "Saint-Jean de Luz Ciboure",
"frhpn" : "Saint-Jean de Maurienne Arvan",
"frhsd" : "Saint-Julien en Genevois",
"frejc" : "Saint-Maixent",
"frxsb" : "Saint-Malo",
"frifg" : "Saint-Marcellin (Isère)",
"friwz" : "Saint-Martin Bellevue",
"frxvr" : "Saint-Michel Valloire",
"frsnr" : "Saint-Nazaire",
"frxsg" : "Saint-Omer",
"frhtt" : "Saint-Pierre en Faucigny",
"frspt" : "Saint-Pol sur Ternoise",
"frxsj" : "Saint-Quentin",
"frxsk" : "Saint-Raphaël Valescure",
"frssl" : "Saint-Sulpice Laurière",
"frxsn" : "Sallanches Combloux Megève",
"frsbg" : "Sarrebourg",
"fracn" : "Saumur",
"frsne" : "Saverne",
"frxsw" : "Sedan",
"frxsq" : "Sélestat",
"frxsf" : "Sens",
"frxsy" : "Sète",
"frfph" : "St Gaudens",
"frxsh" : "St Pierre des Corps",
"fraeg" : "Strasbourg",
"freip" : "Surgères",
"frxtb" : "Tarbes",
"frthp" : "TGV Haute-Picardie",
"frxth" : "Thionville",
"frxts" : "Thonon les Bains",
"frtol" : "Toul",
"frtln" : "Toulon",
"frxyt" : "Toulouse Matabiau",
"fradm" : "Tourcoing",
"frhgq" : "Tournus",
"frafw" : "Tours",
"frtrd" : "Trouville - Deauville",
"frqyr" : "Troyes",
"frifj" : "Tullins-Fures",
"fruss" : "Ussel",
"fraaw" : "Uzerche",
"frvdr" : "Val De Reuil",
"frvaf" : "Valence",
"frfrk" : "Valence d'Agen",
"frvla" : "Valence TGV Rhône Alpes Sud",
"frxvs" : "Valenciennes",
"frhsb" : "Valleiry",
"frvne" : "Vannes",
"fresl" : "Vendôme Villiers sur Loir",
"frdqc" : "Vernon",
"frdht" : "Versailles Chantiers",
"frxvo" : "Vesoul",
"frvhy" : "Vichy",
"frxvi" : "Vienne",
"frxvz" : "Vierzon Ville",
"frfiy" : "Vigeois",
"frduo" : "Villedieu Les Poêles",
"frfup" : "Villefranche de Lauragais",
"frifh" : "Vinay",
"frdux" : "Vire",
"frhvi" : "Virieu sur Bourbre",
"frxvt" : "Vitré",
"frbfo" : "Vitry le François",
"frhnz" : "Viviers du Lac",
"frhvo" : "Voiron",
"frhvq" : "Voreppe"
};

module.exports = {
  code: function(name) {
    for( var prop in city_codes) {
      if (city_codes.hasOwnProperty(prop)) {
        if (city_codes[prop] === name) {
          return prop;
        }
      }
    }
  },
  name: function(code) {
    return city_codes[code];
  },
  all: city_codes
};
